name: Build iOS Capacitor Beta无签名IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: 拉取全部源码
        uses: actions/checkout@v4

      - name: 配置Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装依赖
        run: npm install

      - name: CocoaPods更新&安装
        working-directory: ./ios/App
        run: |
          pod repo update
          pod install

      - name: Xcode归档，关闭签名
        working-directory: ./ios/App
        run: |
          xcodebuild archive \
          -workspace App.xcworkspace \
          -scheme App \
          -sdk iphoneos \
          -configuration Debug \
          -archivePath ../../App.xcarchive \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGN_IDENTITY=""

      - name: 打包成IPA
        run: |
          mkdir Payload
          cp -R ./App.xcarchive/Products/Applications/*.app Payload
          zip -r Sunflower.ipa Payload

      - name: 上传IPA成品
        uses: actions/upload-artifact@v4
        with:
          name: Sunflower安装包
          path: Sunflower.ipa
